#!/usr/bin/env python3
"""[B] Render a run's actual billings as invoice PDFs. Demo material.

    python scripts/generate_invoices.py 15              # write them to data/invoices/15/
    python scripts/generate_invoices.py 15 --upload     # and put them in the run
    python scripts/generate_invoices.py 15 --issuer "Northwind Studio"

**What these are, and what they are not.** ADR-007 draws a hard line: contracts
are *sourced* and actuals are *derived* from them by deterministic arithmetic —
no model ever invents either. These invoices sit on the derived side of that
line and are built the same way. Every figure on every page is read straight out
of `actual_transactions`, which `data_sourcing/scenario_builder.py` computed
from the real EDGAR contracts in the run. Nothing here decides an amount,
rounds one, or makes one up.

So an invoice generated here shows **what was actually billed — including the
mistake.** That is the entire point. Where a run carries a `forgotten_raise`,
the invoice says $5,000 because $5,000 is what went out, while the contract
clause beside it says it should have said $5,500. The document is the evidence,
not an illustration of it.

**A ghost invoice gets no page, deliberately.** A `ghost_invoice` finding means
a billing that never happened, so there is no transaction, so nothing is
rendered for that month. Generating a page there to make the set look complete
would contradict the finding the run is built to demonstrate: the absence *is*
the evidence.

**Every page says it was generated.** Same reasoning as ADR-021's typeset
contract pages, which state in their own footer that they are not the filing as
filed. These are not documents anyone's accounting system produced — they are a
rendering of a ledger this project derived. A page that looked like a genuine
business record while not being one is not demo material, it is a forgery, and
the difference is one line of footer text. Do not remove it.

**Deterministic in content, not in bytes.** Every figure, every invoice number
and every filename is derived from the run's rows — numbers come from the client
and the date, never from a counter, so re-running this does not renumber a demo
you have already screenshotted, and a filename that existed still exists. What
is *not* stable is the PDF bytes: PyMuPDF stamps a fresh document ID on each
save, so two runs produce different sha256 sums for identical pages (measured;
clearing the metadata dict does not fix it). That matters in one place only —
these must not be content-addressed the way `pdf_renderer` caches typeset pages
under `data/cache/pdf/`, because the same invoice would land under a new key
every time. Compare the extracted text, never the hash.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

import pymupdf

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from core.config import PROJECT_ROOT  # noqa: E402
from core.db import database  # noqa: E402
from core.db.models import (  # noqa: E402
    ActualTransaction,
    Anomaly,
    Client,
    ContractRule,
    Document,
    ExpectedTimeline,
    Run,
)

#: A4 in points, matching `core/extraction/pdf_renderer.py` so a demo does not
#: mix page sizes when you page between a contract and an invoice.
PAGE_W, PAGE_H = 595, 842
MARGIN = 56

INK = (0.09, 0.09, 0.10)
MUTED = (0.42, 0.42, 0.45)
RULE = (0.80, 0.80, 0.82)

FOOTER = (
    "Generated by FinSight from this run's own transaction ledger for demonstration. "
    "Not a document issued by any business."
)


#: Base-14 Helvetica is Latin-1 only, and PyMuPDF silently substitutes a middot
#: for anything outside it — an em dash renders as "·", a euro sign renders as
#: "·" too. Silently, on the page, with no warning at write time. So text destined
#: for a PDF goes through `_ascii` first, and any symbol that is not Latin-1 is
#: spelled out rather than mangled. Caught by reading the extracted text of a
#: rendered page, which is the only way this kind of fault ever shows up.
_SUBSTITUTIONS = {
    "\u2014": " - ",  # em dash
    "\u2013": "-",  # en dash
    "\u2018": "'",
    "\u2019": "'",
    "\u201c": '"',
    "\u201d": '"',
    "\u2026": "...",
    "\u20ac": "EUR ",  # euro: not in Latin-1
}


def _ascii(value: str) -> str:
    """Text Helvetica can actually draw. See `_SUBSTITUTIONS`."""
    for bad, good in _SUBSTITUTIONS.items():
        value = value.replace(bad, good)
    return value.encode("latin-1", "replace").decode("latin-1")


def _money(amount: float, currency: str) -> str:
    code = (currency or "USD").upper()
    symbol = {"USD": "$", "GBP": "\u00a3"}.get(code)  # both are Latin-1
    return f"{symbol}{amount:,.2f}" if symbol else f"{amount:,.2f} {code}"


def _invoice_number(client_id: int, when: date, ordinal: int) -> str:
    """Stable, readable, and derived — never a counter.

    A counter would renumber every invoice the moment one more transaction
    landed, which silently invalidates any screenshot taken before it.
    """
    return f"INV-{when:%Y%m}-{client_id:03d}{ordinal:02d}"


def _text(page, x, y, value, *, size=10, bold=False, color=INK, align=0):
    font = "hebo" if bold else "helv"
    value = _ascii(value)
    if align == 2:  # right-aligned against the right margin
        width = pymupdf.get_text_length(value, fontname=font, fontsize=size)
        x = PAGE_W - MARGIN - width
    page.insert_text((x, y), value, fontname=font, fontsize=size, color=color)


def _wrap(value: str, size: float, max_width: float, *, bold: bool = False) -> list[str]:
    """Break text to fit a column. Measured in the font it will be drawn in,
    not guessed from a character count — the terms line is a full sentence and
    a guess overflows the margin on half the contracts in the corpus."""
    font = "hebo" if bold else "helv"
    words, lines, current = _ascii(value).split(), [], ""
    for word in words:
        candidate = f"{current} {word}".strip()
        if pymupdf.get_text_length(candidate, fontname=font, fontsize=size) <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def _rule(page, y, color=RULE, width=0.8):
    page.draw_line(
        pymupdf.Point(MARGIN, y), pymupdf.Point(PAGE_W - MARGIN, y), color=color, width=width
    )


def render_invoice(
    *,
    issuer: str,
    client_name: str,
    number: str,
    issued: date,
    amount: float,
    currency: str,
    description: str,
    reference: str | None,
    contract_file: str | None,
    terms: str | None,
    contract_says: float | None,
) -> bytes:
    """One invoice, as it was actually billed.

    `contract_says` is the expected amount when the run found this billing
    short — it is printed as a discreet note rather than hidden, because a demo
    that makes you take the discrepancy on faith is weaker than one where you
    can read both numbers off the page.
    """
    doc = pymupdf.open()
    page = doc.new_page(width=PAGE_W, height=PAGE_H)
    content_w = PAGE_W - 2 * MARGIN

    y = MARGIN + 14
    _text(page, MARGIN, y, issuer, size=17, bold=True)
    _text(page, MARGIN, y, "INVOICE", size=17, bold=True, align=2)
    y += 10
    _rule(page, y, color=INK, width=1.6)

    # Two columns: who it is for on the left, what it is on the right. The
    # first draft right-aligned all four fields, which put a whole sentence of
    # payment terms against the right margin and read as an afterthought.
    y += 32
    _text(page, MARGIN, y, "BILLED TO", size=8, bold=True, color=MUTED)
    _text(page, MARGIN, y, "INVOICE No.", size=8, bold=True, color=MUTED, align=2)
    y += 17
    _text(page, MARGIN, y, client_name, size=13, bold=True)
    _text(page, MARGIN, y, number, size=11, align=2)
    y += 18
    _text(page, MARGIN, y, f"Issued {issued:%d %B %Y}", size=9.5, color=MUTED, align=2)

    y += 40
    _rule(page, y)
    y += 15
    _text(page, MARGIN, y, "DESCRIPTION", size=8, bold=True, color=MUTED)
    _text(page, MARGIN, y, "AMOUNT", size=8, bold=True, color=MUTED, align=2)
    y += 8
    _rule(page, y)

    y += 25
    _text(page, MARGIN, y, description, size=10.5)
    _text(page, MARGIN, y, _money(amount, currency), size=10.5, align=2)
    for note in (reference, f"Under {contract_file}" if contract_file else None):
        if note:
            y += 13
            _text(page, MARGIN, y, note, size=8.5, color=MUTED)

    y += 20
    _rule(page, y)
    y += 26
    _text(page, MARGIN, y, "Total due", size=12, bold=True)
    _text(page, MARGIN, y, _money(amount, currency), size=15, bold=True, align=2)
    y += 12
    _rule(page, y, color=INK, width=1.2)

    if contract_says is not None and abs(contract_says - amount) >= 0.005:
        y += 30
        for line in _wrap(
            f"FinSight: this run's contract terms support "
            f"{_money(contract_says, currency)} for this period, short by "
            f"{_money(contract_says - amount, currency)}.",
            9,
            content_w,
        ):
            _text(page, MARGIN, y, line, size=9, color=MUTED)
            y += 13

    if terms:
        # Bottom-left, where an invoice's terms actually live.
        ty = PAGE_H - MARGIN - 78
        _text(page, MARGIN, ty, "PAYMENT TERMS", size=8, bold=True, color=MUTED)
        ty += 15
        for line in _wrap(terms, 9, content_w * 0.72):
            _text(page, MARGIN, ty, line, size=9, color=MUTED)
            ty += 12

    # The footer, per the module docstring. Not decoration.
    _rule(page, PAGE_H - MARGIN - 2)
    for i, line in enumerate(_wrap(FOOTER, 7.5, content_w)):
        _text(page, MARGIN, PAGE_H - MARGIN + 12 + i * 10, line, size=7.5, color=MUTED)

    data = doc.tobytes()
    doc.close()
    return data


def build(run_id: int, issuer: str) -> list[tuple[str, bytes]]:
    """Every invoice for a run, as `(filename, pdf_bytes)`, oldest first."""
    with database.session_scope() as session:
        run = session.get(Run, run_id)
        if run is None:
            raise SystemExit(f"no run {run_id} in {database.describe_backend()}")

        clients = {c.id: c for c in session.query(Client).filter(Client.run_id == run_id)}
        rules = {
            r.client_id: r
            for r in session.query(ContractRule).filter(ContractRule.client_id.in_(clients))
        }
        documents = {d.id: d for d in session.query(Document).filter(Document.run_id == run_id)}

        # What the run says each billing *should* have been, so an invoice that
        # came up short can print both figures. Keyed by (client, year, month)
        # because a bank payment lands a few days from its billing date.
        expected: dict[tuple[int, int, int], float] = {}
        for row in session.query(ExpectedTimeline).filter(ExpectedTimeline.run_id == run_id):
            key = (row.client_id, row.billing_date.year, row.billing_date.month)
            expected[key] = expected.get(key, 0.0) + row.expected_amount

        # Only where the run actually found something. A billing that matched
        # its contract gets no note, because there is nothing to say.
        flagged: set[tuple[int, int, int]] = set()
        for anomaly in session.query(Anomaly).filter(Anomaly.run_id == run_id):
            timeline = (
                session.get(ExpectedTimeline, anomaly.expected_timeline_id)
                if anomaly.expected_timeline_id
                else None
            )
            if timeline is not None:
                flagged.add(
                    (anomaly.client_id, timeline.billing_date.year, timeline.billing_date.month)
                )

        transactions = (
            session.query(ActualTransaction)
            .filter(ActualTransaction.run_id == run_id)
            .order_by(ActualTransaction.transaction_date, ActualTransaction.id)
            .all()
        )

        per_month: dict[tuple[int, int, int], int] = defaultdict(int)
        out: list[tuple[str, bytes]] = []

        for txn in transactions:
            client = clients.get(txn.client_id)
            if client is None:
                # Unattributed payments exist on purpose (ADR-020 refuses rather
                # than guesses). An invoice needs a addressee, so they are skipped
                # and reported, not invented a client for.
                continue

            rule = rules.get(client.id)
            key = (client.id, txn.transaction_date.year, txn.transaction_date.month)
            per_month[key] += 1
            number = _invoice_number(client.id, txn.transaction_date, per_month[key])

            contract_file = None
            if rule is not None and rule.document_id in documents:
                contract_file = documents[rule.document_id].filename

            pdf = render_invoice(
                issuer=issuer,
                client_name=client.name,
                number=number,
                issued=txn.transaction_date,
                amount=txn.amount,
                currency=(rule.currency if rule else None) or "USD",
                # A line item a person would write, derived from the contract's
                # own billing frequency. The bank's own string is kept below it
                # as the reference, so the page still shows where it came from.
                description=(
                    f"{(rule.billing_frequency if rule else 'monthly') or 'monthly'}".capitalize()
                    + f" services \u00b7 {txn.transaction_date:%B %Y}"
                ),
                reference=f"Ledger reference: {txn.description}" if txn.description else None,
                contract_file=contract_file,
                terms=rule.payment_terms if rule else None,
                contract_says=expected.get(key) if key in flagged else None,
            )
            out.append((f"{number}_{client.normalized_name or client.id}.pdf", pdf))

        return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("run_id", type=int, help="which run's ledger to render")
    parser.add_argument(
        "--issuer",
        default="Northwind Studio",
        help="the business sending the invoices (the runs do not record one)",
    )
    parser.add_argument(
        "--upload",
        action="store_true",
        help="also record them in the run, so they appear in both frontends",
    )
    parser.add_argument("--out", help="output directory (default data/invoices/<run_id>/)")
    args = parser.parse_args()

    invoices = build(args.run_id, args.issuer)
    if not invoices:
        print(f"run {args.run_id} has no attributable transactions — nothing to render")
        return 1

    out_dir = Path(args.out) if args.out else PROJECT_ROOT / "data" / "invoices" / str(args.run_id)
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, data in invoices:
        (out_dir / name).write_bytes(data)

    total = sum(1 for _ in invoices)
    print(f"wrote {total} invoice(s) to {out_dir}")

    if args.upload:
        from core import ingest

        with database.session_scope() as session:
            result = ingest.ingest_files(session, args.run_id, invoices, category="invoice")
        # Both frontends read through a cache; the Streamlit app has its own.
        try:
            from web import cache as web_cache

            web_cache.clear()
        except Exception:  # pragma: no cover - web/ is optional to this script
            pass
        print(f"recorded {result.recorded} in run {args.run_id} ({len(result.failed)} failed)")
        print(
            "note: an invoice PDF contributes its text, not its money — "
            "`actual_transactions` come from the CSV statement and are unchanged, "
            "so the run's findings are exactly what they were."
        )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
